version: '3.7'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    networks:
      - subnet

  imgservice:
    container_name: imgservice
    build:
      context: ./imgservice
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks: 
      - subnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    networks:
      - subnet

networks:
  subnet: